# Generated by Django 5.1.1 on 2024-11-12 16:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('tipo_documento', models.CharField(choices=[('tarjeta_identidad', 'Tarjeta de Identidad'), ('cedula', 'Cedula'), ('pasaporte', 'Pasaporte'), ('documento_extranjeria', 'Documento de Extranjeria')], max_length=50)),
                ('numero_documento', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_expedicion', models.DateField(null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('lqbt', 'LQBT'), ('prefiero_no_decir', 'Prefiero no decirlo')], max_length=50)),
                ('grupo_sanguineo', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=50)),
                ('eps', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('administrador', 'Administrador')], default='estudiante', max_length=50)),
                ('Nivel_estudio', models.CharField(choices=[('primaria', 'Educacion Primaria'), ('secundaria', 'Educacion Secundaria'), ('tecnico', 'Tecnico Superior'), ('tecnologo', 'Tecnologo'), ('pregrado', 'Pregrado'), ('posgrado', 'Posgrado'), ('maestria', 'Maestria'), ('doctorado', 'Doctorado')], default='pregrado', max_length=50)),
                ('fecha_graduacion', models.DateField(null=True)),
                ('carrera', models.CharField(choices=[('medico', 'Medico'), ('enfermero', 'Enfermero'), ('odontologo', 'Odontologo'), ('farmaceutico', 'Farmaceutico'), ('psicologo', 'Psicologo'), ('fisioterapeuta', 'Fisioterapeuta'), ('nutricionista', 'Nutricionista'), ('veterinario', 'Veterinario'), ('ingeniero_civil', 'Ingeniero Civil'), ('ingeniero_mecanico', 'Ingeniero Mecanico'), ('ingeniero_electrico', 'Ingeniero Electrico'), ('ingeniero_industrial', 'Ingeniero Industrial'), ('ingeniero_informatico', 'Ingeniero Informatico'), ('ingeniero_quimico', 'Ingeniero Quimico'), ('psicologo_social', 'Psicologo Social'), ('sociologo', 'Sociologo'), ('trabajador_social', 'Trabajador Social'), ('antropologo', 'Antropologo'), ('politologo', 'Politologo'), ('artista', 'Artista'), ('disenador_grafico', 'Disenador Grafico'), ('disenador_modas', 'Disenador de Modas'), ('arquitecto', 'Arquitecto'), ('fotografo', 'Fotografo'), ('musico', 'Musico'), ('administrador_empresas', 'Administrador de Empresas'), ('contador', 'Contador'), ('economista', 'Economista'), ('mercadologo', 'Mercadologo'), ('recursos_humanos', 'Recursos Humanos'), ('financiero', 'Financiero'), ('cienciado_computacion', 'Cienciado de la Computacion'), ('desarrollador_software', 'Desarrollador de Software'), ('cibersegurista', 'Cibersegurista'), ('inteligencia_artificial', 'Inteligencia Artificial'), ('analista_datos', 'Analista de Datos'), ('biologo', 'Biologo'), ('quimico', 'Quimico'), ('fisico', 'Fisico'), ('geologo', 'Geologo'), ('ecologo', 'Ecologo'), ('periodista', 'Periodista'), ('relacionista_publico', 'Relacionista Publico'), ('publicista', 'Publicista'), ('comunicador_audiovisual', 'Comunicador Audiovisual'), ('productor_medios', 'Productor de Medios'), ('abogado', 'Abogado'), ('notario', 'Notario'), ('abogado_internacional', 'Abogado Internacional'), ('abogado_ambiental', 'Abogado Ambiental')], max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('semestre', models.CharField(choices=[('semestre_1', 'Primer Semestre'), ('semestre_2', 'Segundo Semestre'), ('semestre_3', 'Tercer Semestre'), ('semestre_4', 'Cuarto Semestre'), ('semestre_5', 'Quinto Semestre'), ('semestre_6', 'Sexto Semestre'), ('semestre_7', 'Septimo Semestre'), ('semestre_8', 'Octavo Semestre'), ('semestre_9', 'Noveno Semestre'), ('semestre_10', 'Decimo Semestre')], max_length=50)),
                ('tarjeta_profesional', models.CharField(max_length=50)),
                ('titulo', models.CharField(choices=[('medico', 'Medico'), ('enfermero', 'Enfermero'), ('odontologo', 'Odontologo'), ('farmaceutico', 'Farmaceutico'), ('psicologo', 'Psicologo'), ('fisioterapeuta', 'Fisioterapeuta'), ('nutricionista', 'Nutricionista'), ('veterinario', 'Veterinario'), ('ingeniero_civil', 'Ingeniero Civil'), ('ingeniero_mecanico', 'Ingeniero Mecanico'), ('ingeniero_electrico', 'Ingeniero Electrico'), ('ingeniero_industrial', 'Ingeniero Industrial'), ('ingeniero_informatico', 'Ingeniero Informatico'), ('ingeniero_quimico', 'Ingeniero Quimico'), ('psicologo_social', 'Psicologo Social'), ('sociologo', 'Sociologo'), ('trabajador_social', 'Trabajador Social'), ('antropologo', 'Antropologo'), ('politologo', 'Politologo'), ('artista', 'Artista'), ('disenador_grafico', 'Disenador Grafico'), ('disenador_modas', 'Disenador de Modas'), ('arquitecto', 'Arquitecto'), ('fotografo', 'Fotografo'), ('musico', 'Musico'), ('administrador_empresas', 'Administrador de Empresas'), ('contador', 'Contador'), ('economista', 'Economista'), ('mercadologo', 'Mercadologo'), ('recursos_humanos', 'Recursos Humanos'), ('financiero', 'Financiero'), ('cienciado_computacion', 'Cienciado de la Computacion'), ('desarrollador_software', 'Desarrollador de Software'), ('cibersegurista', 'Cibersegurista'), ('inteligencia_artificial', 'Inteligencia Artificial'), ('analista_datos', 'Analista de Datos'), ('biologo', 'Biologo'), ('quimico', 'Quimico'), ('fisico', 'Fisico'), ('geologo', 'Geologo'), ('ecologo', 'Ecologo'), ('periodista', 'Periodista'), ('relacionista_publico', 'Relacionista Publico'), ('publicista', 'Publicista'), ('comunicador_audiovisual', 'Comunicador Audiovisual'), ('productor_medios', 'Productor de Medios'), ('abogado', 'Abogado'), ('notario', 'Notario'), ('abogado_internacional', 'Abogado Internacional'), ('abogado_ambiental', 'Abogado Ambiental')], max_length=100)),
                ('experiencia_laboral', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', models.FloatField(default=0, null=True)),
                ('nota_2', models.FloatField(default=0, null=True)),
                ('nota_3', models.FloatField(default=0, null=True)),
                ('faltas', models.PositiveIntegerField(default=0)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('habilitable', models.BooleanField(default=True)),
                ('nivel_educativo', models.CharField(choices=[('primaria', 'Educacion Primaria'), ('secundaria', 'Educacion Secundaria'), ('tecnico', 'Tecnico Superior'), ('tecnologo', 'Tecnologo'), ('pregrado', 'Pregrado'), ('posgrado', 'Posgrado'), ('maestria', 'Maestria'), ('doctorado', 'Doctorado')], max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materias',
            field=models.ManyToManyField(related_name='asignaciones', to='core.materia'),
        ),
    ]
